---
- name: Destroy VM
  hosts: localhost
  gather_facts: false
  vars_files:
    - vars.yml
  environment:
    VCENTER_HOSTNAME: "{{ vcenter_hostname | default(lookup('ansible.builtin.env', 'VCENTER_HOSTNAME')) }}"
    VCENTER_USERNAME: "{{ vcenter_username | default(lookup('ansible.builtin.env', 'VCENTER_USERNAME')) }}"
    VCENTER_PASSWORD: "{{ vcenter_password | default(lookup('ansible.builtin.env', 'VCENTER_PASSWORD')) }}"
    VCENTER_VALIDATE_CERTS: "{{ vcenter_validate_certs | default(lookup('ansible.builtin.env', 'VCENTER_VALIDATE_CERTS')) }}"

  pre_tasks:
    - name: Check Inputs
      ansible.builtin.assert:
        that: vcenter_resource_prefix
        fail_msg: You must set the variable vcenter_resource_prefix to some string

  tasks:
    - name: Power Off VM
      community.vmware.vmware_guest:
        name: "{{ test_vm_name }}"
        folder: "{{ vcenter_folder }}"
        cluster: "{{ vcenter_cluster }}"
        datacenter: "{{ vcenter_datacenter }}"
        state: poweredoff
    - name: Destroy VM
      community.vmware.vmware_guest:
        name: "{{ test_vm_name }}"
        folder: "{{ vcenter_folder }}"
        cluster: "{{ vcenter_cluster }}"
        datacenter: "{{ vcenter_datacenter }}"
        state: absent
    - name: Destroy Folder
      vmware.vmware.folder:
        datacenter: "{{ vcenter_datacenter }}"
        folder_type: vm
        relative_path: "{{ vcenter_folder }}"
        state: absent
